#---------------------------------------------------------------------------------
#Before running this code: read README.md
#---------------------------------------------------------------------------------


#You can uncomment the plt.save line in order to save the plot

import numpy as np
import pandas as pd
from pydicom import dcmread
import os
import re
import argparse
import matplotlib.pyplot as plt



parser = argparse.ArgumentParser()
parser.add_argument("-t", "--TopasFolderPath", nargs='?', help="The input directory of the Patient TOPAS-scripts folder. It should include subfolders with the different Beams.", default=".")
parser.add_argument("-r", "--RTDoseFolderPath", nargs='?', help="The input directory of the Patient, including rtdose, rtplan and the subfolder 'RTDose_BeamX_CPs'. ", default=".")
parser.add_argument("-o", "--OutputPath", nargs='?', help="The output directory where the plot and txt will be saved. ", default="/tmp")
parser.add_argument("-b", "--BeamNumber", type=int, nargs='+', help="A list of beam numbers where a separate calibration.txt is calculated, format: [BeamNumber_i, ..]", default=[])

args = parser.parse_args()

print(f"Topas folder path: {args.TopasFolderPath}")
print(f"RTDose folder path: {args.RTDoseFolderPath}\n")
print("-----------------------------------\n")

#Function to extract the number of bins and the size of the bins in cm for each axis from the header file generated by topas, this information is needed to reshape the dose arrays correctly

def extract_binheader(path):
    data = {}
    format = re.compile(r"# ([XYZ]) in (\d+) bins of ([\d.]+) cm")
    print(f"Extracting binheader information from: {path}")
    try:
        with open(path, 'r') as f:
            for line in f:
                match = format.search(line)
                if match:
                    axis = match.group(1)
                    num_bins = int(match.group(2))
                    shape = float(match.group(3))
                    
                    data[axis] = {
                        "bins": num_bins,
                        "size_cm": shape
                    }
        return data
    except FileNotFoundError:
        return "Error: Binheader file not found."

for beamnumber in args.BeamNumber:
    print(f"Working on calibration for Beamnumber: {beamnumber}")
  
    dcmcp_path = args.RTDoseFolderPath + f"/RTDose_Beam{beamnumber}_CPs"
    dwcp_path = os.path.join(args.TopasFolderPath, f"Beam_{beamnumber}")
    if not os.path.exists(dcmcp_path) or not os.path.exists(dwcp_path):
        print(f"Skipping Beam {beamnumber}: Missing one or both required folders.")
        print(f"   - RTDose Path exists: {os.path.exists(dcmcp_path)}")
        print(f"   - Topas Path exists: {os.path.exists(dwcp_path)}")
        continue 
    # =========================RTDOSE=============================================    
    rows_dicom = []
    number_dcmfiles=0
    for file in os.listdir(dcmcp_path):
        if file.startswith('rtdose_beam1_CP'):
            number_dcmfiles=number_dcmfiles+1
            match = re.search(r'CP(\d+)', file) 
            cp = int(match.group(1))
            path = os.path.join(dcmcp_path, file)
            rtdose_cp = dcmread(path)
            dose_cp = rtdose_cp.pixel_array*rtdose_cp.DoseGridScaling
            max_rt = np.max(dose_cp)
            mean_rt = np.mean(dose_cp)
            sum_rt = np.sum(dose_cp)
            rows_dicom.append([cp,max_rt,mean_rt,sum_rt])
    print(f'Number of RTDose files read: {number_dcmfiles}')
    df_dicom = pd.DataFrame(rows_dicom, columns=['CP', 'Max Dose', 'Mean Dose', 'Sum Dose'])

    # =========================RTPLAN============================================
    plan_path = args.RTDoseFolderPath +"/rtplan.dcm"
    rtplan = dcmread(plan_path)
    beam = rtplan.IonBeamSequence[0]
    cp_to_energy = {}
    for i, cp in enumerate(beam.IonControlPointSequence):
        if i % 2 == 0 and hasattr(cp, "NominalBeamEnergy"): 
            cp_to_energy[i] = cp.NominalBeamEnergy

    # =========================TOPAS=============================================

    #Since every .bin file is generated with the same voxel grid, we can read the dimensions of the grid from the file with the complete dose and use it for all the files
    #This information is saved in the .binheader file generated by topas
    #We will look for the binheader coming from the complete beamlet range: Dw_patient_PPH#
    for bin_file in os.listdir(args.TopasFolderPath+f"/Beam_{beamnumber}"):
        if bin_file.endswith('.binheader') and bin_file.startswith('Dw_patient_PPH'): 
            pph_s = (bin_file.split('H')[1].split('.')[0])
    pph=float(pph_s)
    binheader_path = args.TopasFolderPath +f"/Beam_{beamnumber}"+ f"/Dw_patient_PPH{pph_s}.binheader" 
    binheader = extract_binheader(binheader_path)
    print(f'Binheader information: {binheader}\n')
    nx, ny, nz = binheader['X']['bins'], binheader['Y']['bins'], binheader['Z']['bins']
    dx, dy, dz = binheader['X']['size_cm'], binheader['Y']['size_cm'], binheader['Z']['size_cm']
    total_voxels = nx * ny * nz

    #=========================TOPAS CPs=============================================
    
    rows_topas = []
    number_files=0

    for file in os.listdir(dwcp_path):

        if file.startswith('Dw_patient_CP') and file.endswith('.bin'): #just bin files 
            match = re.search(r'CP(\d+)', file) #this way we can save the CP number to which it corresponds
            number_files=number_files+1
            cp = int(match.group(1))
            path = os.path.join(dwcp_path, file)
            dose_cp = np.fromfile(path,dtype='<d')
            dose_cp = dose_cp.reshape((nz, ny, nx))
            max_cp = np.max(dose_cp)
            mean_cp = np.mean(dose_cp)
            sum_cp = np.sum(dose_cp)
            rows_topas.append([cp,max_cp,mean_cp,sum_cp])
    print(f'Number of Topas .bin files read: {number_files}')

    df_topas = pd.DataFrame(rows_topas, columns=['CP', 'Max Dose', 'Mean Dose', 'Sum Dose'])


    # =========================CALIBRATION============================================

    df_calibration = pd.merge(df_topas[['CP', 'Mean Dose']], df_dicom[['CP', 'Mean Dose']], on='CP', suffixes=('_topas', '_rtdose'))
    df_calibration['Calibration Factor'] = (df_calibration['Mean Dose_rtdose'] / df_calibration['Mean Dose_topas'])/pph
    df_calibration['Energy'] = df_calibration['CP'].map(cp_to_energy)
    df_calibration = df_calibration.sort_values(by='Energy')
  
    plt.figure(figsize=(10, 6))
    plt.scatter(df_calibration['Energy'], df_calibration['Calibration Factor'], color='blue', label='Calibration Factor')
    plt.title(f'Calibration Factor vs Energy for {pph} Particles Per History')
    plt.xlabel('Energy [MeV]')
    plt.ylabel('Calibration Factor')
    plt.grid(True)
    plt.show()
#    plt.savefig(f'{args.OutputPath}/Calibration_beam{beamnumber}.pdf')

    calibration_output_path = os.path.join(args.OutputPath, "calibration_beam{beamnumber}.txt")
    df_calibration.to_csv(calibration_output_path, columns=['Energy', 'Calibration Factor'], index=False, header=False, sep='\t')

