import os
import argparse
from pydicom import dcmread

parser = argparse.ArgumentParser()
parser.add_argument("-i", "--inputPath", nargs='?', help="The input directory containing the DICOM files of the different proton patients generated by writeTROTStoDICOM.py, format: C:\Your\Directory\DICOMs\Protons", default="/tmp")

args = parser.parse_args()


for patient_folder in os.listdir(args.inputPath):
    patient_path = os.path.join(args.inputPath, patient_folder)
    if os.path.isdir(patient_path):
        print(f"Processing patient folder: {patient_folder}")
    
        for file in os.listdir(patient_path):
            if file.endswith('plan.dcm'):
                plan_file_path=os.path.join(patient_path, file)
                rtplan = dcmread(plan_file_path)                           
                for beam in rtplan.IonBeamSequence:
                    beam_number = beam.BeamNumber
                    print(f'Copy and paste the following control points for {patient_folder} beam {beam_number}\n')
                    print('[')
                    #For each control point, we will extract the number of scan spots and print it in a list
                    numb_scanspots = []
                    cp_numbers = []
                    for i, cp in enumerate(beam.IonControlPointSequence):
                        if i % 2 == 0 and hasattr(cp, "NumberOfScanSpotPositions") : 
                            numb_scanspots.append(cp.NumberOfScanSpotPositions)
                            cp_numbers.append(cp.ControlPointIndex) 
                            print(f'({beam_number},{i}),')
                    print(']')
