import os
import argparse
from pydicom import dcmread

parser = argparse.ArgumentParser()
parser.add_argument("-i", "--inputPath", nargs='?', help="The input directory containing the DICOM files of the different proton patients generated by writeTROTStoDICOM.py, format: C:\Your\Directory\DICOMs\Protons", default="/tmp")
parser.add_argument("-p", "--printSP", nargs='?', help="Set to True in order to print instead of [(BeamNumber_i, CP_i),...], print [(BeamNumber_i,CP_i,BeamSpotNumber_i), ... ] ", default=True)

args = parser.parse_args()
printSP = args.printSP if isinstance(args.printSP, bool) else args.printSP == "True"


for patient_folder in os.listdir(args.inputPath):
    patient_path = os.path.join(args.inputPath, patient_folder)
    if os.path.isdir(patient_path):
        print(f"Processing patient folder: {patient_folder}")
        cp_file = os.path.join(patient_path, "cp_file.txt")
        sp_file = os.path.join(patient_path, "sp_file.txt")
        with open(sp_file, "w", encoding="utf-8") as f: f.write('')
        with open(cp_file, "w", encoding="utf-8") as f: f.write('')

        for file in os.listdir(patient_path):
            if file.endswith('plan.dcm'):
                plan_file_path=os.path.join(patient_path, file)
                rtplan = dcmread(plan_file_path)                           
                for beam in rtplan.IonBeamSequence:
                    beam_number = beam.BeamNumber
                    numb_scanspots = []
                    for i, cp in enumerate(beam.IonControlPointSequence):
                        if i % 2 == 0 and hasattr(cp, "NumberOfScanSpotPositions") : 
                            if printSP:
                                acc=0
                                numb_scanspots=cp.NumberOfScanSpotPositions
                                for k in range(int(numb_scanspots)):
                                    with open(sp_file, "a", encoding="utf-8") as f:
                                        f.write(f'({beam_number},{i},{k+1}),')
                            else:
                                with open(cp_file, "a", encoding="utf-8") as f:
                                    f.write(f'({beam_number},{i}),')                            
