#This code will read the DICOM files generated by writeTROTStoDICOM.py and create the necessary input files for topas, which will be used to run the simulations and obtain the dose for each control point (energy layer) in order to perform the calibration with the rtdose files.
#Inside the specified output directory, a folder for each patient will be created, and inside this folder the folders for each beam, and inside each beam folder, the files for each control point with the correct number of scan spots to simulate will be created.



import os
import argparse
from pydicom import dcmread

parser = argparse.ArgumentParser()
parser.add_argument("-s", "--OutputPath", nargs='?', help="The output directory of the binary files where topas is compiled, note that it should contain beam.txt and plan_hu.txt, from your computer.", default="/rti.git/rti/topas/")
parser.add_argument("-i", "--inputPath", nargs='?', help="The input directory containing the DICOM files of the different proton patients generated by writeTROTStoDICOM.py, format: C:\Your\Directory\DICOMs\Protons", default="/tmp")
parser.add_argument("-d", "--ParticlesperHistory", nargs='?', help="Decimation factor of particles in RTplan, or by how much the number of histories is scaled down to have a reasonable computation time", default=1)

args = parser.parse_args()

#Since Topas has trouble reading Windows directories, we will change the format of the directories to the Linux/WSL one
def convert_path_format(windows_path):
    abs_path = os.path.abspath(windows_path)
    path = abs_path.replace('\\', '/')
    #If the path starts with a drive letter (such as C:), we need to convert it to /mnt/c
    if ':' in path:
        drive, rest = path.split(':', 1)
        path = f"/mnt/{drive.lower()}{rest}"
    return path

#In order to compile the run_CPX txt files we need to include plan_hu.txt which appears in previous folders, so we need to change the path from beam folder to just keep the path to 
def get_linuxpath(path):
    path = path.replace('\\', '/')
    
    if path.startswith('//wsl.localhost/') or path.startswith('//wsl$/'):
        parts = path.split('/')
        # parts[0] y [1] are empty due to //
        # parts[2] is 'wsl.localhost' orr 'wsl$'
        # parts[3] name  'Ubuntu-24.04'
        # The rest is the real path: /home/leyla/...
        return '/' + '/'.join(parts[4:])
    
    return path

print(f"Input path: {args.inputPath}")
print(f"Output path: {args.OutputPath}\n")
print("-----------------------------------\n")

for patient_folder in os.listdir(args.inputPath):
    patient_path = os.path.join(args.inputPath, patient_folder)
    if os.path.isdir(patient_path):
        print(f"Processing patient folder: {patient_folder}")
        #We will create a folder for each patient
        patient_folder_path = os.path.join(args.OutputPath, f"{patient_folder}")

        os.makedirs(patient_folder_path, exist_ok=True)
        for file in os.listdir(patient_path):
            if file.endswith('plan.dcm'):
                plan_file_path=os.path.join(patient_path, file)
                #For each beam inside RT Plan, we will create inside --OutputPath, as many folders as beams
                rtplan = dcmread(plan_file_path)
                #In order to obtain the Position of the Image Center, we need to read the patient first and last CT
                #Since not all patients have the same number of CT slices, we will read all the CT files and find the one with the lowest and highest z coordinate, which will correspond to the first and last CT respectively
                max_ct=1000
                min_ct=0
                
                for ct_file in os.listdir(patient_path):
                    if ct_file.endswith('.dcm') and ct_file.startswith('CT_'): 
                        #We can extract the CT number from the file name, which is in the format CT_X.dcm, where X is the CT number:
                        ct_number = int(ct_file.split('_')[1].split('.')[0])
                        if ct_number > min_ct:
                            max_ct= ct_number
                            last_ct_path = os.path.join(patient_path, ct_file)
                        if ct_number < max_ct:
                            min_ct = ct_number
                            first_ct_path = os.path.join(patient_path, ct_file)
                
                #Now we can read the first and last CT to obtain the coordinates of the image center, which we will use later to position the patient in topas
                first_ct = dcmread(first_ct_path)
                first_ct_coordinates = first_ct.ImagePositionPatient
                last_ct = dcmread(last_ct_path)
                last_ct_coordinates = last_ct.ImagePositionPatient
                
                #The coordinates of the image center of each slice have to be calculated taking into account the pixel spacing and the number of voxels in each direction
                #Since it is the same plan, we can extract the spacing and thickness from the first CT
                pixel_spacing = first_ct.PixelSpacing 
                slice_thickness = first_ct.SliceThickness 
                num_voxels_x = first_ct.Columns
                num_voxels_y = first_ct.Rows
                #The coordinates from the DICOM files correspond to the center of the first voxel, so we need to add half of the pixel spacing to get the coordinates of the center of the image
                x_i= first_ct_coordinates[0] - (pixel_spacing[0] / 2)
                y_i= first_ct_coordinates[1] - (pixel_spacing[1] / 2)
                z_i= first_ct_coordinates[2] - (slice_thickness / 2)
                x_f= x_i+ (num_voxels_x + 1) * pixel_spacing[0] 
                y_f= y_i+ (num_voxels_y + 1) * pixel_spacing[1]
                z_f= z_i+ (max_ct + 1) * slice_thickness

                img_center_x = (x_i + x_f) / 2
                img_center_y = (y_i + y_f) / 2
                img_center_z = (z_i + z_f) / 2
                #Now we can create the plan.txt file for each patient:

                with open(os.path.join(patient_folder_path, "plan.txt"), "w", encoding="utf-8") as f:
                    f.write(f"""
includeFile = {ppal_path}/beam.txt

####################################################
##------ Overriding parameters        -----
####################################################

Ge/World/HLX = 110.0 cm
Ge/World/HLY = 110.0 cm
Ge/World/HLZ = 110.0 cm
Ge/World/Material = "Air"

####################################################
##------ RTION as layered mass geometry        -----
####################################################
#sv:Ph/Default/LayeredMassGeometryWorlds = 1 "RTION" 

####################################################
#----------------- RTIonComponent ------------------
####################################################
# RTION geometry is parallel
Ge/RTION/IsParallel     = "F"

# ---
# 1. Patient CT to calculate 
# Image center in Patient DICOM coordinate system
# Iso center in Patient DICOM coordinate 
# As TOPAS places center of patient CT at the origin, 
# ---
s:Ge/RTION/ImgDirectory = Rt/RTION/CTDirectory
dc:Ge/RTION/ImgCenterX  = {img_center_x} mm
dc:Ge/RTION/ImgCenterY  = {img_center_y} mm
dc:Ge/RTION/ImgCenterZ  = {img_center_z} mm

# ---
# 2. Position RTIon components (only beamline component)
# this will not affect dose-grid
# ---

Ge/RTION/TransX = Ge/RTION/IsoCenterX - Ge/RTION/ImgCenterX mm
Ge/RTION/TransY = Ge/RTION/IsoCenterY - Ge/RTION/ImgCenterY mm
Ge/RTION/TransZ = Ge/RTION/IsoCenterZ - Ge/RTION/ImgCenterZ mm

# ---
# 3. Rotation RTIon components (only beamline components) 
# ---
#RotCollimator/Gantry/PatientSupport/IEC2DICOM are RTION specific
Ge/RTION/RotCollimator      = Ge/RTION/CollimatorAngle deg
Ge/RTION/RotGantry          = Ge/RTION/GantryAngle deg
Ge/RTION/RotPatientSupport  = -1.0 * Ge/RTION/PatientSupportAngle deg
Ge/RTION/RotIEC2DICOM       = 90 deg 

####################################################
#----------------- RTIonSource  --------------------
####################################################
# ---
# 1. Patient CT to calculate 
# ---
s:So/RTION/ImgDirectory = Rt/RTION/CTDirectory
dc:So/RTION/ImgCenterX  = {img_center_x} mm
dc:So/RTION/ImgCenterY  = {img_center_y} mm
dc:So/RTION/ImgCenterZ  = {img_center_z} mm


# ---
# 2. Position RTIon components (only beamline component)
# this will not affect dose-grid
# ---
So/RTION/ShiftX = So/RTION/IsoCenterX - So/RTION/ImgCenterX mm
So/RTION/ShiftY = So/RTION/IsoCenterY - So/RTION/ImgCenterY mm
So/RTION/ShiftZ = So/RTION/IsoCenterZ - So/RTION/ImgCenterZ mm

So/RTION/RotCollimator      = So/RTION/CollimatorAngle deg
So/RTION/RotGantry          = So/RTION/GantryAngle deg
So/RTION/RotPatientSupport  = -1.0 * So/RTION/PatientSupportAngle deg


####################################################
##------ DICOM Patient  -----
####################################################

s:Ge/Patient/Type     = "TsDicomPatient"
s:Ge/Patient/Parent   = "IEC_F"
s:Ge/Patient/Material = "G4_WATER"
s:Ge/Patient/DicomDirectory      = Rt/RTION/CTDirectory
s:Ge/Patient/CloneRTDoseGridFrom = Rt/RTION/RTDoseFile

d:Ge/Patient/TransX   = 0.0 mm 

d:Ge/Patient/TransY   = 0.0 mm
d:Ge/Patient/TransZ   = 0.0 mm 

d:Ge/Patient/RotX     = 0. deg
d:Ge/Patient/RotY     = 0. deg
d:Ge/Patient/RotZ     = 0. deg
# Specify which slices to show.
# Comment this out or set to zero to show all slices.
# Set to -1 to show only center slice.
# Set to -2 to show first, center and last slice.
#para poner la primera empieza en 1, no en 0
#iv:Ge/Patient/ShowSpecificSlicesX = 1 -1
#iv:Ge/Patient/ShowSpecificSlicesY = 1 -1
iv:Ge/Patient/ShowSpecificSlicesZ  = 1 1
b:Ge/Patient/IgnoreInconsistentFrameOfReferenceUID = "True"

b:Ge/Patient/IsVisible = "True"
s:Ge/Patient/DrawingStyle = "FullWireFrame"
sv:Ge/Patient/DicomModalityTags = 1 "CT"

####################################################
#----------------- Scorers --------------------
####################################################
s:Sc/RTDose/Quantity    = "DoseToWater"
s:Sc/RTDose/Component   = "Patient/RTDoseGrid" 
#s:Sc/RTDose/OutputFile="Dw_patient_PPH10"
s:Sc/RTDose/OutputType  = "binary" 
s:Sc/RTDose/IfOutputFileAlreadyExists = "OverWrite" # Exit, Overwrite or Increment
b:Sc/RTDose/PreCalculateStoppingPowerRatios = "True"
b:Sc/RTDose/OutputToConsole = "FALSE"
""")
                    
                #Now we have to create an input file for each patient, where the directories are specified. Note that the beam number has to be manually changed, as well as Particles per History

                for beam in rtplan.IonBeamSequence:
                    beam_number = beam.BeamNumber
                    beam_folder_path = os.path.join(patient_folder_path, f"Beam_{beam_number}")
                    os.makedirs(beam_folder_path, exist_ok=True)
                    #Firts we will need to use the path conversion function:
                    patient_path_linux = convert_path_format(patient_path)

                    with open(os.path.join(beam_folder_path, "inputs.txt"), "w", encoding="utf-8") as f:
                        f.write(f"s:Rt/RTION/PlanFile = \"{patient_path_linux}/rtplan.dcm\"\n")
                        f.write(f"s:Rt/RTION/RTDoseFile = \"{patient_path_linux}/rtdose.dcm\"\n")
                        f.write(f"s:Rt/RTION/CTDirectory = \"{patient_path_linux}\"\n")
                        f.write(f"u:Rt/RTION/ParticlesPerHistory = {args.ParticlesperHistory}\n")
                        f.write(f"i:Rt/RTION/BeamNumberToBeSimulated = {beam_number}\n")

                    #Now for each control point, we will extract the number of scan spots and save it in a list, which we will use later to create the files for each control point with the correct number of scan spots
                    numb_scanspots = []
                    for i, cp in enumerate(beam.IonControlPointSequence):
                        if i % 2 == 0 and hasattr(cp, "NumberOfScanSpotPositions") : #hasattr() takes as arguments an object and the name of an attribute, returns True if the object contains that attribute
                            numb_scanspots.append(cp.NumberOfScanSpotPositions)
                    
                    ppal_path = get_linuxpath(args.OutputPath) #We need to go up two levels to get the path where plan_hu.txt is located, which is needed to compile the run_CPX txt files

                    acc=0
                    for i, num_spots in enumerate(numb_scanspots):
                        start = acc + 1
                        end = acc + num_spots
                        cp_id = i * 2
                        
                        file_name = f"run_CP{cp_id}.txt"
                        output_name = f"Dw_patient_CP{cp_id}"
                        full_path = os.path.join(beam_folder_path ,file_name)
                        with open(full_path, "w", encoding="utf-8") as f:
                            f.write(f"includeFile={ppal_path}/plan_hu.txt\n")
                            f.write(f"s:Sc/RTDose/OutputFile = \"{output_name}\"\n")
                            f.write(f"iv:So/RTION/BeamletRange = 2 {start} {end}\n")
                                                
                        acc += num_spots

    print(f"Finished processing patient folder: {patient_folder} \n\n")




